### ISSUE TITLE
Background image?

### ISSUE THREAD

**Issue by yairEO** [dixonandmoe/rellax#108]
It isn't mentioned anywhere how to parallax a background image, which is a very common use-case

**Comment by moeamaya** [comment]
Appreciate the suggestion and will potentially add to the 2.0 version. But closing since this isn't an issue, but suggestion.

**Comment by divdax** [comment]
+1

**Comment by hidegh** [comment]
This is a way to mimic and use BG images with rellax.

```html
  <div class="rellax-bg-container" style="height: 50vh;">
    <div>
      <h1>Rellax text</h1>
    </div>
    
    <div class="rellax rellax-bg background-image-business"></div>
  </div>
```

```css
    .rellax-bg-container {
      position: relative;
      overflow: hidden;
    }

    .rellax-bg {
        position: absolute;
        top: 0;
        width: 100%;
        height: 100%; /* height has to be extended +50-100% if positive parallax scroll value is used */
        z-index: -5000;
    }
 ```
